### ISSUE TITLE
missing emb_cate_w.txt

### ISSUE THREAD

**Issue by ANDYWANGTIANTIAN** [yuzhimanhua/SeeTopic#2]
`(SeeTopic) PS D:\SeeTopic> sh ./seetopic.sh                
===Get PLM Embeddings===
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 55902/55902 [06:34<00:00, 141.74it/s]
===Iter 0: PLM Module===
===Iter 1: PLM Module===
===Iter 1: Local Module===
make: 'cate' is up to date.
./run_local.sh: line 15: ./src/cate: cannot execute binary file: Exec format error
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\get_local_nn.py", line 21, in <module>
    with open(f'{dataset}_{num_iter}/emb_cate_w.txt') as fin:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs_1/emb_cate_w.txt'
===Iter 1: Ensemble===
Traceback (most recent call last):
  File "ensemble.py", line 24, in <module>
    with open(f'{dataset}/keywords_{model}_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_local_2.txt'
===Iter 2: PLM Module===
Traceback (most recent call last):
  File "get_bert_nn.py", line 17, in <module>
    with open(f'{dataset}/keywords_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_2.txt'
===Iter 2: Local Module===
make: 'cate' is up to date.
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\prepare.py", line 12, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin, open(f'{dataset}_{num_iter}/keywords.txt', 'w') as fout:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_2.txt'
./run_local.sh: line 15: ./src/cate: cannot execute binary file: Exec format error
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\get_local_nn.py", line 15, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_2.txt'
===Iter 2: Ensemble===
Traceback (most recent call last):
  File "ensemble.py", line 24, in <module>
    with open(f'{dataset}/keywords_{model}_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_biobert_3.txt'
===Iter 3: PLM Module===
Traceback (most recent call last):
  File "get_bert_nn.py", line 17, in <module>
    with open(f'{dataset}/keywords_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_3.txt'
===Iter 3: Local Module===
make: 'cate' is up to date.
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\prepare.py", line 12, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin, open(f'{dataset}_{num_iter}/keywords.txt', 'w') as fout:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_3.txt'
./run_local.sh: line 15: ./src/cate: cannot execute binary file: Exec format error
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\get_local_nn.py", line 15, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_3.txt'
===Iter 3: Ensemble===
Traceback (most recent call last):
  File "ensemble.py", line 24, in <module>
    with open(f'{dataset}/keywords_{model}_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_biobert_4.txt'
===Iter 4: PLM Module===
Traceback (most recent call last):
  File "get_bert_nn.py", line 17, in <module>
    with open(f'{dataset}/keywords_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_4.txt'
===Iter 4: Local Module===
make: 'cate' is up to date.
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\prepare.py", line 12, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin, open(f'{dataset}_{num_iter}/keywords.txt', 'w') as fout:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_4.txt'
./run_local.sh: line 15: ./src/cate: cannot execute binary file: Exec format error
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\get_local_nn.py", line 15, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_4.txt'
===Iter 4: Ensemble===
Traceback (most recent call last):
  File "ensemble.py", line 24, in <module>
    with open(f'{dataset}/keywords_{model}_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_biobert_5.txt'
cp: cannot stat 'scidocs/keywords_5.txt': No such file or directory`

**Comment by ANDYWANGTIANTIAN** [comment]
(SeeTopic) PS D:\SeeTopic> sh ./seetopic.sh                
===Get PLM Embeddings===
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 55902/55902 [06:34<00:00, 141.74it/s]
===Iter 0: PLM Module===
===Iter 1: PLM Module===
===Iter 1: Local Module===
make: 'cate' is up to date.
./run_local.sh: line 15: ./src/cate: cannot execute binary file: Exec format error
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\get_local_nn.py", line 21, in <module>
    with open(f'{dataset}_{num_iter}/emb_cate_w.txt') as fin:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs_1/emb_cate_w.txt'
===Iter 1: Ensemble===
Traceback (most recent call last):
  File "ensemble.py", line 24, in <module>
    with open(f'{dataset}/keywords_{model}_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_local_2.txt'
===Iter 2: PLM Module===
Traceback (most recent call last):
  File "get_bert_nn.py", line 17, in <module>
    with open(f'{dataset}/keywords_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_2.txt'
===Iter 2: Local Module===
make: 'cate' is up to date.
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\prepare.py", line 12, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin, open(f'{dataset}_{num_iter}/keywords.txt', 'w') as fout:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_2.txt'
./run_local.sh: line 15: ./src/cate: cannot execute binary file: Exec format error
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\get_local_nn.py", line 15, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_2.txt'
===Iter 2: Ensemble===
Traceback (most recent call last):
  File "ensemble.py", line 24, in <module>
    with open(f'{dataset}/keywords_{model}_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_biobert_3.txt'
===Iter 3: PLM Module===
Traceback (most recent call last):
  File "get_bert_nn.py", line 17, in <module>
    with open(f'{dataset}/keywords_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_3.txt'
===Iter 3: Local Module===
make: 'cate' is up to date.
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\prepare.py", line 12, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin, open(f'{dataset}_{num_iter}/keywords.txt', 'w') as fout:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_3.txt'
./run_local.sh: line 15: ./src/cate: cannot execute binary file: Exec format error
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\get_local_nn.py", line 15, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_3.txt'
===Iter 3: Ensemble===
Traceback (most recent call last):
  File "ensemble.py", line 24, in <module>
    with open(f'{dataset}/keywords_{model}_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_biobert_4.txt'
===Iter 4: PLM Module===
Traceback (most recent call last):
  File "get_bert_nn.py", line 17, in <module>
    with open(f'{dataset}/keywords_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_4.txt'
===Iter 4: Local Module===
make: 'cate' is up to date.
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\prepare.py", line 12, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin, open(f'{dataset}_{num_iter}/keywords.txt', 'w') as fout:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_4.txt'
./run_local.sh: line 15: ./src/cate: cannot execute binary file: Exec format error
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\get_local_nn.py", line 15, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_4.txt'
===Iter 4: Ensemble===
Traceback (most recent call last):
  File "ensemble.py", line 24, in <module>
    with open(f'{dataset}/keywords_{model}_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_biobert_5.txt'
cp: cannot stat 'scidocs/keywords_5.txt': No such file or directory

**Comment by ANDYWANGTIANTIAN** [comment]
(SeeTopic) PS D:\SeeTopic> sh ./seetopic.sh                
===Get PLM Embeddings===
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 55902/55902 [06:34<00:00, 141.74it/s]
===Iter 0: PLM Module===
===Iter 1: PLM Module===
===Iter 1: Local Module===
make: 'cate' is up to date.
./run_local.sh: line 15: ./src/cate: cannot execute binary file: Exec format error
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\get_local_nn.py", line 21, in <module>
    with open(f'{dataset}_{num_iter}/emb_cate_w.txt') as fin:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs_1/emb_cate_w.txt'
===Iter 1: Ensemble===
Traceback (most recent call last):
  File "ensemble.py", line 24, in <module>
    with open(f'{dataset}/keywords_{model}_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_local_2.txt'
===Iter 2: PLM Module===
Traceback (most recent call last):
  File "get_bert_nn.py", line 17, in <module>
    with open(f'{dataset}/keywords_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_2.txt'
===Iter 2: Local Module===
make: 'cate' is up to date.
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\prepare.py", line 12, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin, open(f'{dataset}_{num_iter}/keywords.txt', 'w') as fout:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_2.txt'
./run_local.sh: line 15: ./src/cate: cannot execute binary file: Exec format error
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\get_local_nn.py", line 15, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_2.txt'
===Iter 2: Ensemble===
Traceback (most recent call last):
  File "ensemble.py", line 24, in <module>
    with open(f'{dataset}/keywords_{model}_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_biobert_3.txt'
===Iter 3: PLM Module===
Traceback (most recent call last):
  File "get_bert_nn.py", line 17, in <module>
    with open(f'{dataset}/keywords_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_3.txt'
===Iter 3: Local Module===
make: 'cate' is up to date.
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\prepare.py", line 12, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin, open(f'{dataset}_{num_iter}/keywords.txt', 'w') as fout:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_3.txt'
./run_local.sh: line 15: ./src/cate: cannot execute binary file: Exec format error
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\get_local_nn.py", line 15, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_3.txt'
===Iter 3: Ensemble===
Traceback (most recent call last):
  File "ensemble.py", line 24, in <module>
    with open(f'{dataset}/keywords_{model}_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_biobert_4.txt'
===Iter 4: PLM Module===
Traceback (most recent call last):
  File "get_bert_nn.py", line 17, in <module>
    with open(f'{dataset}/keywords_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_4.txt'
===Iter 4: Local Module===
make: 'cate' is up to date.
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\prepare.py", line 12, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin, open(f'{dataset}_{num_iter}/keywords.txt', 'w') as fout:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_4.txt'
./run_local.sh: line 15: ./src/cate: cannot execute binary file: Exec format error
Traceback (most recent call last):
  File "D:\SeeTopic\seed_guided_emb\get_local_nn.py", line 15, in <module>
    with open(f'../{dataset}/keywords_{num_iter}.txt') as fin:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../scidocs/keywords_4.txt'
===Iter 4: Ensemble===
Traceback (most recent call last):
  File "ensemble.py", line 24, in <module>
    with open(f'{dataset}/keywords_{model}_{num_iter}.txt') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'scidocs/keywords_biobert_5.txt'
cp: cannot stat 'scidocs/keywords_5.txt': No such file or directory

**Comment by yuzhimanhua** [comment]
Hi,

I think the error starts from:
```
./run_local.sh: line 15: ./src/cate: cannot execute binary file: Exec format error
```

Looks like you were running the script under a Windows environment. Could you check if you can execute a compiled C++ file? Here, ./src/cate is a compiled C++ file.

**Comment by ANDYWANGTIANTIAN** [comment]
thank you for your reply, it do seems to be the windows issue, i will try to run this code on linux later.

this is when i try to make cate:

> (SeeTopic) PS D:\SeeTopic\seed_guided_emb\src> make
gcc cate.c -o cate -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result
cate.c: In function 'LoadEmb':
cate.c:386:7: warning: implicit declaration of function 'posix_memalign' [-Wimplicit-function-declaration]
  386 |   a = posix_memalign((void **) &syn_tmp, 128, (long long) layer1_size * sizeof(real));
      |       ^~~~~~~~~~~~~~
cate.c:386:42: warning: 'posix_memalign' argument 2 type is 'int' where 'long long unsigned int' is expected in a call to built-in function declared without prototype [-Wbuiltin-declaration-mismatch]
  386 |   a = posix_memalign((void **) &syn_tmp, 128, (long long) layer1_size * sizeof(real));
      |                                          ^~~
<built-in>: note: built-in 'posix_memalign' declared here
cate.c: In function 'ReadTopic':
cate.c:452:18: warning: implicit declaration of function 'getline' [-Wimplicit-function-declaration]
  452 |   while ((read = getline(&line, &len, fp)) != -1) {
      |                  ^~~~~~~
cate.c: In function 'InitNet':
cate.c:531:39: warning: 'posix_memalign' argument 2 type is 'int' where 'long long unsigned int' is expected in a call to built-in function declared without prototype [-Wbuiltin-declaration-mismatch]
  531 |   a = posix_memalign((void **) &syn0, 128, (long long) vocab_size * layer1_size * sizeof(real));
  886 |     for (a = 0; a < num_threads; a++) pthread_create(&pt[a], NULL, TrainEmb, (void *) a);
      |                                                                              ^
cate.c: In function 'TrainEmb':
cate.c:788:1: warning: control reaches end of non-void function [-Wreturn-type]
  788 | }
      | ^
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\andy\AppData\Local\Temp\ccp5B0Zu.o:cate.c:(.text+0x21e2): undefined reference to `posix_memalign'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\andy\AppData\Local\Temp\ccp5B0Zu.o:cate.c:(.text+0x2900): undefined reference to `getline'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\andy\AppData\Local\Temp\ccp5B0Zu.o:cate.c:(.text+0x3ad7): undefined reference to `posix_memalign'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\andy\AppData\Local\Temp\ccp5B0Zu.o:cate.c:(.text+0x3b01): undefined reference to `posix_memalign'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\andy\AppData\Local\Temp\ccp5B0Zu.o:cate.c:(.text+0x3c90): undefined reference to `posix_memalign'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\andy\AppData\Local\Temp\ccp5B0Zu.o:cate.c:(.text+0x3cc2): undefined reference to `posix_memalign'
collect2.exe: error: ld returned 1 exit status

**Comment by ANDYWANGTIANTIAN** [comment]
thank you for your reply, it do seems to be the windows issue, I will try to run this code on linux later.

this is when I try to make cate:

> (SeeTopic) PS D:\SeeTopic\seed_guided_emb\src> make
gcc cate.c -o cate -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result
cate.c: In function 'LoadEmb':
cate.c:386:7: warning: implicit declaration of function 'posix_memalign' [-Wimplicit-function-declaration]
  386 |   a = posix_memalign((void **) &syn_tmp, 128, (long long) layer1_size * sizeof(real));
      |       ^~~~~~~~~~~~~~
cate.c:386:42: warning: 'posix_memalign' argument 2 type is 'int' where 'long long unsigned int' is expected in a call to built-in function declared without prototype [-Wbuiltin-declaration-mismatch]
  386 |   a = posix_memalign((void **) &syn_tmp, 128, (long long) layer1_size * sizeof(real));
      |                                          ^~~
<built-in>: note: built-in 'posix_memalign' declared here
cate.c: In function 'ReadTopic':
cate.c:452:18: warning: implicit declaration of function 'getline' [-Wimplicit-function-declaration]
  452 |   while ((read = getline(&line, &len, fp)) != -1) {
      |                  ^~~~~~~
cate.c: In function 'InitNet':
cate.c:531:39: warning: 'posix_memalign' argument 2 type is 'int' where 'long long unsigned int' is expected in a call to built-in function declared without prototype [-Wbuiltin-declaration-mismatch]
  531 |   a = posix_memalign((void **) &syn0, 128, (long long) vocab_size * layer1_size * sizeof(real));
  886 |     for (a = 0; a < num_threads; a++) pthread_create(&pt[a], NULL, TrainEmb, (void *) a);
      |                                                                              ^
cate.c: In function 'TrainEmb':
cate.c:788:1: warning: control reaches end of non-void function [-Wreturn-type]
  788 | }
      | ^
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\andy\AppData\Local\Temp\ccp5B0Zu.o:cate.c:(.text+0x21e2): undefined reference to `posix_memalign'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\andy\AppData\Local\Temp\ccp5B0Zu.o:cate.c:(.text+0x2900): undefined reference to `getline'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\andy\AppData\Local\Temp\ccp5B0Zu.o:cate.c:(.text+0x3ad7): undefined reference to `posix_memalign'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\andy\AppData\Local\Temp\ccp5B0Zu.o:cate.c:(.text+0x3b01): undefined reference to `posix_memalign'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\andy\AppData\Local\Temp\ccp5B0Zu.o:cate.c:(.text+0x3c90): undefined reference to `posix_memalign'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\andy\AppData\Local\Temp\ccp5B0Zu.o:cate.c:(.text+0x3cc2): undefined reference to `posix_memalign'
collect2.exe: error: ld returned 1 exit status
